version: 2
updates:
  # npm workspace dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "tungcodeforfun"
    assignees:
      - "tungcodeforfun"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "tungcodeforfun"
    assignees:
      - "tungcodeforfun"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"